Job coloring rework
Nyanotrasen/Nyanotrasen pull request #1504
Opened 2023-04-16 17:00 UTC by FluffiestFloof

## About the PR 
Rework Job, ID card and Encryption keys so it is a bit more fitting overall. Probably needs discussion for certain colors, icon choices etc.
For example the Valet would make sense to put under Cargo/Logistics colors but eh.
They are still all under HoP supervision.

Is this a big list for what amounts to tiny sprite changes? Yes, I wanted to be thorough with this for some reason.

Trying to follow the previously set color scheme of the "Service" departement jobs, they are split into Logistics/Cargo(Brown), Catering(Green), Civilian(Grey) and "Entertainment"(Pink).

- Job icons changes
  - Assistant is a better letter A.
  - Roboticist now uses Engineering departement colors even if unused.
  - Valet now reuses the sprite for the Service encryption key as it fits relatively well.
  - Gladiator gets a new sprite in the form a sword and the same colors as the prisoner icon.
  - Martial Artist gets a new sprite in the form of a karate chop hand or something like that.
  - Reporter changes into Civilian grey.
  - Cyborg and MedicalCyborg gets job icons.

- Encryption key changes
  - Renames the "science" encryption keys to "epistemic" encryption keys
  - Salvage and QM encryption keys sprites uses their corect color even if unused.
  - Roboticist encryption card now uses Engineering departement colors even if unused.
  - The Common encryption key now uses the Assistant job icon sprite.

- ID Card changes
  - Salvage now uses the Miner sprites which has been recoloured to the Engineering departement
  - Roboticist now uses Engineering departement colors even if unused.
  - Assistant now has a proud A instead of a P.
  - Valet uses the new job icon that somewhat looks like someone holding a plate.
  - Chaplain, Mantis, Mystagogue and Acolyte now uses Epistemic departement colors, white and black.
  - Cataloguer now uses the Librarian sprite which has been recolored to the Epistemic departement colors.
  - Martial Artist gets a new ID icon similar to their new job icon.
  - Gladiator now uses the gladiator job icon and the same colors as the prisoner icon.
  - Boxer, Martial Artist, Musician get a pink icon and trim
  - Lawyer, Reporter and Janitor have a grey icon and trim
  
- Job Spawner changes using the wiki icons I made previously.
  - Add sprites for Gladiator, Martial Artist, Boxer, Valet, Mail Carrier and Musician spawners.
  - Replaces the spawner sprites for; Scientist, Lawyer, Reporter, Librarian, Paramedic, RD, Janitor to better fit our current uses of them and how they look.
  
- Various changes
  - Musician supervisor is now the HoP instead of "Anyone that hires you"
  - Using the Locale for the supervisors instead of plain text (mostly mystagogue)

**Media**
**Changes to the encryption key sprites**
Left to right; Common, MedEpi, Epi, Roboticist, Salvage, QM, Mysta
![encryptChange](https://user-images.githubusercontent.com/9823203/232327844-e6dcb0b1-64fb-4514-8bf7-7956198d1573.png)
In game
![ss (2023-04-16 at 06 25 31)](https://user-images.githubusercontent.com/9823203/232327852-f1c663af-6dff-4824-b5a2-ae5d2aae92d2.png)
<br>

**Changes to the job icons sprites**
Left to right; Assistant, Roboticist, Valet, Gladiator, Martial Artist, Reporter
![jobChange](https://user-images.githubusercontent.com/9823203/232328040-9a3c3111-9fe3-40b3-9180-318e1087b4e2.png)
In game
![ss (2023-04-16 at 06 26 37)](https://user-images.githubusercontent.com/9823203/232327940-fda345dd-589e-4f7b-ae25-c1dbb84ade08.png)
Cyborg job icons
![ss (2023-04-16 at 06 49 04)](https://user-images.githubusercontent.com/9823203/232328104-5e266ce0-3b65-4be1-b5df-f2d048c72e52.png)
<br>

**Changes to the ID card icons sprites**
Left to right; Assistant, Salvage, Roboticist, Valet, Mantis, Cataloguer, Chaplain, Acolyte, Mysta, Boxer, Gladiator, Martial Artist, Janitor, Reporter, Lawyer, Musician
![idChange](https://user-images.githubusercontent.com/9823203/232328000-d9289d1e-9939-4753-b54a-c25caf33f564.png)
Service sub department visualized; Civilian, Catering, Cargo and Entertainment
![ss (2023-04-16 at 06 25 36)](https://user-images.githubusercontent.com/9823203/232328014-fb2b14ac-d158-4395-ac40-b65cef70b9a6.png)
Epistemics
![ss (2023-04-16 at 06 25 38)](https://user-images.githubusercontent.com/9823203/232328016-78a67247-4d13-4838-be3e-5499da3bdb44.png)
Salvage Tech gets their own ID too
![ss (2023-04-16 at 06 25 39)](https://user-images.githubusercontent.com/9823203/232328018-9630fce1-12b5-4e5f-adc7-c28c5e22e573.png)

**Changelog**

:cl:
- tweak: Tweaked job and ID card icons to be more fitting.
- add: Added Cyborgs job icons.

2023-04-17 05:41 UTC, Vordenburg commented
This is looking really good.

What's the mystagogue encryption key sprite about? You said the salvage and QM are unused, but is the mystagogue also unused?

2023-04-17 07:28 UTC, FluffiestFloof commented
> This is looking really good.
> 
> What's the mystagogue encryption key sprite about? You said the salvage and QM are unused, but is the mystagogue also unused?


Yep pretty much unused.
I think it's due to upstream going for more of a "department" encryption keys instead of "role" encryption keys.
See the service key being the cargo sprite for exemple I guess.

2023-04-17 15:20 UTC, Vordenburg commented
Criticisms I can think of at the moment:
- The mime icon says more Space Invaders than mime to me.
- Is there a better icon we can have for the valet? At first glance, I thought the reporter was the valet, because it looked like a bell (bellhop).
- The Epi encryption key looks like an H but I can see how it's supposed to be an !.
- Do the `A`s look better if you use 2 pixels of spacing instead of 1 between the top and middle line?

2023-04-17 15:37 UTC, FluffiestFloof commented
> Criticisms I can think of at the moment:
> 
>     * The mime icon says more Space Invaders than mime to me.
> 
>     * Is there a better icon we can have for the valet? At first glance, I thought the reporter was the valet, because it looked like a bell (bellhop).
> 
>     * The Epi encryption key looks like an H but I can see how it's supposed to be an !.
> 
>     * Do the `A`s look better if you use 2 pixels of spacing instead of 1 between the top and middle line?

* The mime icon is unchanged from upstream and I don't see what else it could be personally. 
* Reporter icon is from upstream, just less green now. We could go back to the green A for valet, I thought using the service icon from the encryption key would look better for the valet. Or actually thinking about it, a V for Valet.
* I just followed the pattern of using the job icon for the encryption key icon. Might be because epistemic are the only one not using white for the actual icon and instead uses black.
* It looks different;
![ss (2023-04-17 at 05 36 39)](https://user-images.githubusercontent.com/9823203/232537629-76d39ab0-0fd2-4041-89bb-2450d1164c92.png)
![ss (2023-04-17 at 05 36 55)](https://user-images.githubusercontent.com/9823203/232537652-86e34705-2abc-4ef3-bac9-b07aa5ea2d7b.png)

2023-04-17 15:38 UTC, Vordenburg commented
2 pixel spacing A looks more balanced to me.

2023-04-17 15:55 UTC, FluffiestFloof commented
For the Valet we could ignore the service icon (which looks like someone holding a plate or something) and just do a V
![ss (2023-04-17 at 05 54 08)](https://user-images.githubusercontent.com/9823203/232542301-c85ef029-f5de-46a1-86ed-e695db2e4890.png)
![ss (2023-04-17 at 05 54 48)](https://user-images.githubusercontent.com/9823203/232542308-839801f9-b766-469f-b23d-d8bf863d72a4.png)

2023-05-09 05:43 UTC, Vordenburg requested changes
I think we're ready to go on this after these couple lines are made consistent with the epistemics headset.

2023-05-09 05:43 UTC, Vordenburg commented on Resources/Prototypes/Catalog/Fills/Boxes/general.yml
> +  name: epistemic encryption key box
```suggestion
  name: epistemics encryption key box
```

2023-05-09 05:43 UTC, Vordenburg commented on Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
> +  name: epistemic encryption key
```suggestion
  name: epistemics encryption key
```

2023-05-09 12:50 UTC, Vordenburg approved these changes

2023-05-09 12:51 UTC, merged