Adds Maintenance lights
Nyanotrasen/Nyanotrasen pull request #1554
Opened 2023-05-09 17:25 UTC by ChilbroBaggins

Changelog:

- Adds 2 variants of maintenance lights (red and white)
- Adds appropriate boxes/crates/cargo
- Tweaks black and red colored lights (reason is so you can have the same effect with less # of lights mapped.)
- Organizes all Nyano-specific lights into 1 location/file.
- Updates appropriate spawners

2023-05-11 12:52 UTC, Elijahrane requested changes

2023-05-11 12:52 UTC, Elijahrane commented on Resources/Prototypes/Nyanotrasen/Catalog/Fills/Boxes/general.yml
> +  id: BoxMaintenancelightbulb
inconsistent camelcasing here, you alternate between 'Maintenancelight... and MaintenanceLight...'. Please choose one (probably the second) and use it for all protos

2023-05-11 13:32 UTC, IamVelcroboy commented on Resources/Prototypes/Nyanotrasen/Catalog/Fills/Boxes/general.yml
> +  id: BoxMaintenancelightbulb
That was an oops. I fixed all the other cases I could find as well.

2023-05-12 13:44 UTC, Elijahrane requested changes

2023-05-12 13:44 UTC, Elijahrane commented on Resources/Prototypes/Nyanotrasen/Markers/Spawners/Random/randomitems.yml
> +      - WeaponDisablerPractice
out of scope and undocumented change?

2023-05-12 13:46 UTC, IamVelcroboy commented on Resources/Prototypes/Nyanotrasen/Markers/Spawners/Random/randomitems.yml
> +      - WeaponDisablerPractice
Ooo, somehow that must have bled through from another branch where I was updating the spawners with new items. I was planning to add it anyway. Do you need me to remove?

2023-05-12 13:51 UTC, Elijahrane commented on Resources/Prototypes/Nyanotrasen/Markers/Spawners/Random/randomitems.yml
> +      - WeaponDisablerPractice
remove it from this pr

2023-05-12 13:53 UTC, ChilbroBaggins commented on Resources/Prototypes/Nyanotrasen/Markers/Spawners/Random/randomitems.yml
> +      - WeaponDisablerPractice
Is done

2023-05-12 13:56 UTC, Elijahrane approved these changes

2023-05-12 13:56 UTC, merged