Re welders
Nyanotrasen/Nyanotrasen pull request #1656
Opened 2023-06-17 08:37 UTC by FluidRock

## About the PR 

Added the ability to reverse engineer advanced welders along with a minor buff to the Experminetal Welding tool.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- tweak: Experimental welding tool now welds slightly faster.
- add: Reverse engineering machine can now analyze Industrial, Advanced Industrial and Experimental Welding tools.

2023-06-17 15:31 UTC, Elijahrane commented
![image](https://github.com/Nyanotrasen/Nyanotrasen/assets/60792108/30e626d0-e654-4cd2-9b48-13c6fa388906)

This can be fixed by either just giving ifrit welder an RE of itself or removing its advanced welder parenting

2023-06-17 15:57 UTC, Vordenburg commented
The infinite fuel welder probably shouldn't be reverse-engineerable. The ifrit hand could use its own entity at some point, but if the infinite fuel welder isn't made RE-able, then that becomes a much lower priority issue.

2023-06-20 03:18 UTC, Vordenburg requested changes

2023-06-20 03:18 UTC, Vordenburg commented on Resources/Prototypes/Entities/Objects/Tools/welders.yml
> +
```suggestion
```

2023-06-20 03:18 UTC, Vordenburg commented on Resources/Prototypes/Entities/Objects/Tools/welders.yml
> +    speed: 1.3
This change should be directed to Wizard's Den.

2023-06-25 13:18 UTC, closed without merging