Glimmer Monitor Cartridge/Program
Nyanotrasen/Nyanotrasen pull request #1677
Opened 2023-06-26 22:33 UTC by Elijahrane

Part of resolving https://github.com/Nyanotrasen/Nyanotrasen/issues/1676

I'm gonna see if I can expand it to be nice-looking and maybe plot a graph of glimmer at various points in time.
I'll remove the grammateus radio spam in the grammateus PR.

:cl: Rane
- add: Epi PDAs now come with a program to monitor glimmer.

2023-06-28 15:08 UTC, Vordenburg requested changes
I left some of my thoughts at first glance. Very cool feature.

2023-06-28 15:08 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/cartridges.yml
> +    state: cart-psi
A separate RSI in a Nyano directory will help to reduce merge conflicts in the future.

2023-06-28 15:08 UTC, Vordenburg commented on Resources/Textures/Objects/Devices/cartridge.rsi/meta.json
> +    },
See comment about separate RSI.

2023-06-28 15:08 UTC, Vordenburg commented on Content.Server/CartridgeLoader/Cartridges/GlimmerMonitorCartridgeSystem.cs
> +namespace Content.Server.CartridgeLoader.Cartridges;
Can these files not be placed in a Nyano directory?

2023-06-28 15:08 UTC, Vordenburg commented on Content.Client/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml.cs
> +    public GlimmerMonitorUiFragment()
```suggestion
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public GlimmerMonitorUiFragment()
```

2023-06-28 15:08 UTC, Vordenburg commented on Content.Server/CartridgeLoader/Cartridges/GlimmerMonitorCartridgeSystem.cs
> +    }
Is there some future plan for UpdateUiState, or can this be condensed into OnUiReady?

2023-06-28 15:08 UTC, Vordenburg commented on Content.Client/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml.cs
> +        var graph = new GlimmerGraph(_resourceCache, new List<int>{ 0, 20, 40, 40, 80, 150, 130, 210, 220, 270, 250, 310, 400, 420, 390, 500});
Are these test values to demonstrate how it works?

2023-06-28 15:08 UTC, Vordenburg commented on Content.Client/Nyanotrasen/UserInterface/CustomControls/GlimmerGraph.cs
> +                handle.DrawLine((15 + i * spacing, 230), (15 + i * spacing, 30), Color.FromHex("#686868"));
These magic numbers could be lifted out and given names as constants to help with legibility.

2023-07-06 21:55 UTC, Elijahrane commented
okay, now should be good for review

2023-07-07 17:46 UTC, Vordenburg requested changes
There's one or two other things I want to look over when I get time again, but this should be the bulk of my review.

2023-07-07 17:46 UTC, Vordenburg commented on Content.Client/Nyanotrasen/CartridgeLoader/Cartridges/GlimmerMonitorUi.cs
> +using Content.Client.CartridgeLoader.Cartridges;
Sorting. Any style you prefer, so long as it's internally consistent. I tend to put System, Robust, then Content, and within Robust/Content I alphasort except in the case of sub-namespacing. I.e.:

```
using Content.Server.Atmos;
using Content.Server.Atmos.Components;
```

2023-07-07 17:46 UTC, Vordenburg commented on Content.Client/Nyanotrasen/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml.cs
> +using System.Linq;
Sorting.

2023-07-07 17:46 UTC, Vordenburg commented on Content.Client/Nyanotrasen/UserInterface/CustomControls/GlimmerGraph.cs
> +{
File-based namespacing.

2023-07-07 17:46 UTC, Vordenburg commented on Content.Client/Nyanotrasen/UserInterface/CustomControls/GlimmerGraph.cs
> +        public GlimmerGraph(IResourceCache resourceCache, List<int> glimmer)
```suggestion
        private static int YOffsetTop => YOffset - 200;
        
        public GlimmerGraph(IResourceCache resourceCache, List<int> glimmer)
```

2023-07-07 17:46 UTC, Vordenburg commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +        private int _i;
More descriptive name?

2023-07-07 17:46 UTC, Vordenburg commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +
Would it not make more sense to have this instruction closer to where it's checked? I see no exit logic between here and line 67.

2023-07-07 17:46 UTC, Vordenburg commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +                GlimmerValues.Add(_glimmerSystem.Glimmer);
I'm assuming this adds values to a list indefinitely. Not an issue with current values, but if the frequency is ever increased, a limit might have to be placed on this like a rotating queue.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/cartridges.yml
> +    netsync: false
The need for `netsync: false` on Sprite was removed when SpriteComponent became a client-only component. This line can go.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +          - Cartridge
These values are copied from BasePDA, right? Must you re-specify them, or will inheritance take care of this?

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +    uiKey: enum.PDAUiKey.Key
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +    uiKey: enum.PDAUiKey.Key
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +          - Cartridge
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +    uiKey: enum.PDAUiKey.Key
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +          - Cartridge
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +    uiKey: enum.PDAUiKey.Key
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/pda.yml
> +          - Cartridge
See note about BasePDA inheritance.

2023-07-07 17:46 UTC, Vordenburg commented on Resources/Locale/en-US/cartridge-loader/cartridges.ftl
> +glimmer-monitor-sync = Sync
I'm thinking it's time we start moving Nyano localizations out into their own folders and files. If you don't want to do it for just this specific string set for this PR, that's fine, but it's something I have on my list to eventually do.

2023-07-07 17:46 UTC, Vordenburg commented on Content.Shared/Nyanotrasen/CartridgeLoader/Cartridges/GlimmerMonitorUiState.cs
> +
```suggestion

```

2023-07-07 17:46 UTC, Vordenburg commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +            SubscribeLocalEvent<RoundRestartCleanupEvent>(Reset);
```suggestion
            SubscribeLocalEvent<RoundRestartCleanupEvent>(OnRoundRestartCleanup);
```

2023-07-07 17:46 UTC, Vordenburg commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +        private void Reset(RoundRestartCleanupEvent args)
```suggestion
        private void OnRoundRestartCleanup(RoundRestartCleanupEvent args)
```

2023-07-07 17:46 UTC, Vordenburg commented on Content.Client/Nyanotrasen/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml.cs
> +        return returnList;
```suggestion
    private List<int> GetAveragedList(IEnumerable<int> glimmerValues, int interval)
    {
        var returnList = new List<int>();

        var subtotal = 0;
        var elementsPassed = 0;
        for (int i = 0; i < glimmerValues.Count(); ++i)
        {
            subtotal += glimmerValues.ElementAt(i);

            ++elementsPassed;
            if (elementsPassed == interval)
            {
                returnList.Add(subtotal / interval);
                subtotal = 0;
                elementsPassed = 0;
            }
        }

        if (elementsPassed != 0)
            returnList.Add(subtotal / elementsPassed);

        return returnList;
    }
```

Let me know if you like this rewrite. I only tested it in a local console to make sure it works. It functions differently at interval boundaries (off by one) but otherwise seems to line up with your original function without creating new lists for every slice.

2023-07-07 17:46 UTC, Vordenburg commented on Content.Client/Nyanotrasen/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml.cs
> +        {
```suggestion
        }
        else if (IntervalButton10.Pressed)
        {
```

2023-07-07 21:56 UTC, Elijahrane commented on Content.Client/Nyanotrasen/UserInterface/CustomControls/GlimmerGraph.cs
> +{
Uhhh, it has it?

2023-07-07 21:59 UTC, Elijahrane commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +                GlimmerValues.Add(_glimmerSystem.Glimmer);
I don't plan to ever increase the frequency

2023-07-07 22:16 UTC, Elijahrane commented on Content.Client/Nyanotrasen/CartridgeLoader/Cartridges/GlimmerMonitorUiFragment.xaml.cs
> +        return returnList;
It works fine, and we can use all the client perf we can get.

2023-07-16 16:12 UTC, Vordenburg commented on Content.Client/Nyanotrasen/UserInterface/CustomControls/GlimmerGraph.cs
> +{
I was referring to file-scoped namespacing, as in, a one-line namespace statement that won't add an extra indent to the file.

2023-07-16 16:19 UTC, Vordenburg requested changes
This looks almost ready to go.

2023-07-16 16:19 UTC, Vordenburg commented on Content.Client/Nyanotrasen/UserInterface/CustomControls/GlimmerGraph.cs
> +                Vector2 vector2 = (XOffset + (i + 1) * spacing, YOffset - _glimmer[i + 1] / 5);
Will probably need to use `var X = new Vector2(...)` or `= new(...)` with System.Numerics using, since the last cherrypick.

2023-07-16 16:19 UTC, Vordenburg commented on Content.Server/Nyanotrasen/Psionics/Glimmer/PassiveGlimmerReductionSystem.cs
> +        private void Reset(RoundRestartCleanupEvent args)
This is still `Reset`? My concern with the name was that Reset's a verb and `On...` would at least be explicitly an event handler.

2023-07-17 21:45 UTC, Elijahrane commented
Should be good other than the "new Vector2" stuff looking a bit ugly. If that is fine or can't be easily improve we can just merge I think

2023-07-19 05:42 UTC, Vordenburg approved these changes

2023-07-19 05:55 UTC, merged