Psionic Content
Nyanotrasen/Nyanotrasen pull request #542
Opened 2022-10-01 23:39 UTC by ZeroDayDaemon

## About the PR 
Adds a few pieces of psionic clothing
:cl:
- add: Added new psionic clothing.

2022-10-01 23:42 UTC, Elijahrane requested changes

2022-10-01 23:42 UTC, Elijahrane commented on Content.Server/Nyanotrasen/Abilities/Psionics/Abilities/NoosphericZapPowerSystem.cs
> +            if (!(TryComp<DamageableComponent>(args.Target, out var damageable) && damageable.DamageContainerID == "Biological"))
your test component should be if they have PotentialPsionicComponent

2022-10-01 23:42 UTC, Elijahrane commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/PsionicClothing.yml
> +    - Telepathic
telepathic isn't a channel

2022-10-02 00:05 UTC, Elijahrane commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/PsionicClothing.yml
> +#Functionality not coded yet
dont really want placeholders for these

2022-10-02 00:06 UTC, Elijahrane commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/PsionicClothing.yml
> +#Functionality not coded yet
just delete the headsets

2022-10-02 00:11 UTC, ZeroDayDaemon commented
Yeah tests are failing, yeah its the tests fault not my code

2022-10-02 00:12 UTC, Elijahrane commented
the failures look related to your code

2022-10-02 00:16 UTC, ZeroDayDaemon commented
> the failures look related to your code

Well you're lookin wrong then

2022-10-02 15:28 UTC, Elijahrane commented
get rid of the copy + pasted pacify variable names
  and Trycomp out var damageable in the zap power

2022-10-02 15:48 UTC, ZeroDayDaemon commented
> get rid of the copy + pasted pacify variable names and Trycomp out var damageable in the zap power

You also need to fix your variable names for powers, since I didnt even base this on pacify

2022-10-02 15:50 UTC, Elijahrane commented
already did

2022-10-02 16:07 UTC, Elijahrane approved these changes

2022-10-02 16:18 UTC, merged