Buff Shields
Nyanotrasen/Nyanotrasen pull request #895
Opened 2022-12-22 23:40 UTC by Leander-0

## About the PR 

Buffed all shields in the game to a somewhat more useful state.

**Changelog**

:cl: Leander
- tweak: Buffed Shields

2022-12-23 20:01 UTC, Vordenburg requested changes

2022-12-23 20:01 UTC, Vordenburg commented on Resources/Prototypes/Damage/modifier_sets.yml
> +    Heat: 0.5
The active should at least duplicate the passive values, otherwise you lose the damage reduction.

2022-12-23 20:01 UTC, Vordenburg commented on Resources/Prototypes/Damage/modifier_sets.yml
> +    Piercing: 0.6
Missing active slash reduction when passive had it.

2022-12-23 20:01 UTC, Vordenburg commented on Resources/Prototypes/Damage/modifier_sets.yml
>  - type: damageModifierSet
This appears to be missing the coefficients from the passive version.

2022-12-23 20:01 UTC, Vordenburg commented on Resources/Prototypes/Damage/modifier_sets.yml
> +    Piercing: 2
These flat reductions would be in effect when the user is holding the item. Flat reductions can be significantly more powerful than any armor, because they do not result in a percentage drop and can remove any incoming damage completely if it is low enough. Keep in mind that these are constructable.

2022-12-23 20:01 UTC, Vordenburg commented on Resources/Prototypes/Damage/modifier_sets.yml
>      Heat: 0.8
Missing the shock coefficient from the passive.

2022-12-23 21:11 UTC, Leander-0 commented
this changes should resolve all the issues stated above

2022-12-23 21:28 UTC, Leander-0 commented on Resources/Prototypes/Damage/modifier_sets.yml
> +    Heat: 0.5
done and made sure the rest of the shields follow the same scheme

2022-12-24 10:29 UTC, Elijahrane approved these changes

2022-12-24 10:31 UTC, merged